[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200