services:
  - type: web
    name: keystone-infra-website
    env: node
    buildCommand: npm run build
    startCommand: node simple-windows-server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 80