services:
  - type: web
    name: keystone-infra-website
    env: node
    buildCommand: npm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html